
tests:

# TODO(chdent): Maybe this should do something?
- name: access currently purposeless root
  url: /
  response_headers:
      content-type: text/plain; charset=UTF-8
  response_strings:
      - nom
